import './globals.css'
import type { Metadata } from 'next'
import { M_PLUS_1p } from 'next/font/google'

const mPlus1p = M_PLUS_1p({ weight: ['100', '300', '400', '500', '700', '800', '900'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={mPlus1p.className}>{children}</body>
    </html>
  )
}
